dist: coverage
language: node_js
node_js:
  - "8"
env:
  - CODECOV_TOKEN="e017b5a7-8e7d-4b63-9bfb-075153165ce0"
install:
  - yarn
  - yarn global add codecov
scripts:
  - yarn test
after_success:
  - codecov -f coverage/*.json
